### PR TITLE
run fullstop as integration-test

### PR DESCRIPTION
**Pull request by jbellmann**
The idea is to startup 'fullstop' without spring-boot-maven-plugin to see that configurations and autowiring work as expected. This is not an final solution but it works for the moment. Maybe we should bake it into it's own profile to skip this on some builds.

Easiest way to make sure that a minimum is working.
- Event-Processor is off
- OAuth2-Token-Refresh is off

Shutdown initiated after 2 min by default, but configurable.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zalando-stups/fullstop/pull/178" target="_blank">ReviewNinja

**Comment by harti2006** [comment]
can we please skip the integration tests for the "normal" mvn clean install use-case? Maybe as you already mentioned using profiles. Of course Travis CI should run the integration test profile...

**Comment by harti2006** [comment]
Why not using the Spring Boot `@IntegrationTest` capabilities. Would be much easier to set up.

**Comment by jbellmann** [comment]
uses it's own profile now 'fullstop-startup'

**Comment by jbellmann** [comment]
@harti2006 I will try out running the normal integration-test. Maybe that is really all we need.

**Pull request merged**
