### PR TITLE
#391 add parameter to lifecycle controller

### LINKED ISSUE #391: Filter lifecycle by version
Adapt lifecylce endpoint to include a filter that lets you choose an applications version.

### PR DESCRIPTION
**Pull request by Gregsen**
fixes #391

### CODE REVIEW

**Comment by mrandi** [comment]
👍

**Comment by mrandi** [comment]
👍

**Comment by mrandi** [comment]
:+1:

**Comment by mrandi** [comment]
👍 but link the new readme to the main readme plz

**Comment by Gregsen** [comment]
@mrandi done via #394

**Comment by mrandi** [comment]
:+1:

**Pull request merged**
