### PR TITLE
update violation type

### LINKED ISSUE #358: Misleading Message for SCM_SOURCE_JSON_MISSING
The human readable message for SCM_SOURCE_JSON_MISSING currently is 

> The deployment artifact (Docker image) for this application version is missing the scm-source.json. See http://docs.stups.io/en/latest/user-guide/application-development.html?highlight=scm-source.json#docker for more information.

But as seen on https://github.com/zalando-stups/pierone/issues/66 Pier One ignores the `scm-source.json` if it doesn't have all the required fields, so it is possible for the `scm-source.json` to exist and this error still being raised so the message should read as:

> The deployment artifact (Docker image) for this application version is missing **a valid** scm-source.json. See http://docs.stups.io/en/latest/user-guide/application-development.html?highlight=scm-source.json#docker for more information.

### PR DESCRIPTION
**Pull request by mrandi**
fixes #358

### CODE REVIEW

**Comment by Gregsen** [comment]
(y)

**Comment by harti2006** [comment]
:+1:

**Comment by harti2006** [comment]
:+1:

**Comment by Gregsen** [comment]
:+1:

**Pull request merged**
