### PR TITLE
Fix security groups check

### LINKED ISSUE #487: Security group ports check fails to determine private IP addresses
### Expected behavior
UNSECURED_PUBLIC_ENDPOINT (errorMessage: "Unsecured security group! Only ports 80 and 443 are allowed") should be ignored if the IP range only includes [private IP addresses](https://en.wikipedia.org/wiki/Private_network).

Currently private IPs are only recognized when they start with "172.31", which is insufficient. E.g. a rule that allows inbound from "172.16.0.0/12" was false-positively reported as unsecured public endpoint.

### Step needed
https://github.com/zalando-stups/fullstop/blob/master/fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/utils/Predicates.java needs to be changed to properly detect rules that only apply to private IPs and exclude them

### PR DESCRIPTION
**Pull request by harti2006**
* correctly handle private IP ranges.
* add IPv6 support
* distinguish protocols (tcp, icmp, udp, ...)

Fixes #487

### CODE REVIEW

**Comment by hjacobs** [comment]
This is probably relevant for team teapot, right?

**Comment by harti2006** [comment]
@hjacobs yes, I checked back with @tuxlife and it seems o be ok to allow ICMP traffic from everywhere. With the upcoming improvement we will have way less false-positive violations.

**Comment by ChristianLohmann** [comment]
i accidentally created a review :(

**Comment by ChristianLohmann** [comment]
👍

**Comment by aermakov-zalando** [comment]
I'd add tests for protocol names as well, if they're supposed to be handled.

**Comment by sebastianpoeplau** [comment]
👍

**Comment by sebastianpoeplau** [comment]
👍

**Comment by harti2006** [comment]
:+1:

**Pull request merged**
